#!/bin/bash

limit=1000
keyword="covid"

for i in {1..30}
do
    echo "Day $i"
    snscrape --max-results $limit twitter-search "$keyword since:2020-01-$i until:2020-01-$(expr $i + 1)" >> data/snscrape-twitter-covid-Jan.txt
done
